remote_theme: mistakes/minimal-mistakes  
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"  
title: Incident Response, Active Directory, Cloud Security
subtitle: "Cyber Security"
description: "DFIR, Incident Response, Cyber Security, Active Directory Security, SANS"
url: threathunting.dev
twitter_username: khannaanurag
title: Incident Response, Active Directory and Cloud Security
description: >- # this means to ignore newlines until "baseurl:"
  Incident Response, Active Directory, Cloud Security
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://threathunting.dev/about" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: khannaanurag
github_username:  oceanduck
repository: oceanduck/oceanduck.github.io

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.13.0"
plugins:
  - jekyll-feed

# Site Author
author:
  name             : "Anurag Khanna"
  avatar           : 
  bio              : "Incident Reponse, SANS Certified Instructor, GSE#97"
  location         : Down Under
  linkedin         : khannaanurag 
  twitter          : khannaanurag

  author:
  name     : "Your Name"
  avatar   : "/resources/raw/anurag-pic.jpeg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Somewhere, USA"



# Reading Files
include:
  - .htaccess
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: # true
      share: true
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
related: true
